### ISSUE TITLE
Please Create CRC checksum's

### ISSUE THREAD

**Issue by sirjaymz** [animetosho/node-yencode#1]
Please create CRC checksums for each of the source release files.
SHA1
SHA256
MD5

**Comment by animetosho** [comment]
Hi, I'm not sure what you're asking for exactly - hashes for every file in this repository?  
Is there any reason for this? Would the Git hashes be sufficient? Aren't you able to obtain the hashes yourself?

**Comment by animetosho** [comment]
Closing due to lack of feedback. Feel free to open again if you have something to add.
