### ISSUE TITLE
Clarification on `column_offset` parameter for `encode` and `encodeTo`

### ISSUE THREAD

**Issue by yawaworthy** [animetosho/node-yencode#2]
I noticed the `encode` and `encodeTo` functions take a `col_offset` parameter. I think I understand the idea (pick up where a previous encode left off), but couldn't think of a practical use case and didn't see [your][1] [calls][2] from Nyuu using it (so they [get the default of 0][3]). Is my understanding about it correct, and have you ever had to use it? Thanks.

[1]: https://github.com/animetosho/Nyuu/blob/master/lib/article.js#L298
[2]: https://github.com/animetosho/Nyuu/blob/master/lib/article.js#L370
[3]: https://github.com/animetosho/node-yencode/blob/master/yencode.cc#L937

**Comment by animetosho** [comment]
Yes, your understanding is correct. I can't think of any real practical use for it either (and have never had to use it); I suppose that in theory\*, you could use it for implementing an incremental encoder for super-sized articles, or may be useful for future [loop tiling](https://en.wikipedia.org/wiki/Loop_tiling) optimisations (i.e. for yEnc+CRC), but for now, it's just there in case you ever need it.

\* the functions never return the column they finish with, so it's not really that practical to use. Unfortunately, returning that kind of info is somewhat awkward in Javascript so I've left it out for now.

**Comment by yawaworthy** [comment]
OK, thanks for the very complete answer. :)
