### ISSUE TITLE
Critical characters not escaped when they are the last character of the segment

### ISSUE THREAD

**Issue by smarchers** [animetosho/node-yencode#3]
I noticed when a critical character is the last character in the segment, and thus the last column, it isn't properly escaped. Since NZB decoders are quite tolerant due to how rampant sloppy some yEnc encoders are, this isn't really an issue, but I thought you might want to know.

Example segments from "One-Punch Man - 01 [1080p] [60FPS].mkv" on alt.binaries.multimedia.anime.highspeed:

- XxGaMpDeIcFjFgBdZvJhMpRj-1476083181807@nyuu
- YzGhAqFuFiKgRlHmEsXpPpLz-1476083191679@nyuu
- XkIpTqYpDvZsVfOaTvBrYnBs-1476083197391@nyuu
- NtXvKlEgWhNlNjHvJmItSlFp-1476083197867@nyuu
- EyKhPlTxAsNlJrKtKzKkLyIb-1476083198493@nyuu
- NyWjXsVsXmLjBuSrEmEvJtVr-1476083229079@nyuu
- YeDkCbAuAeGqLjNvHpWqXsVt-1476083233268@nyuu
- BkTbNcBxNxZrWjXcViRpRjNk-1476083250266@nyuu
- SsYbVcAtDoSuKuFtQhKuIrMt-1476083252619@nyuu
- LpLtSaCzPsFqSeKfCeTuEiNt-1476083275955@nyuu
- JcFiQtSrSdEkEqDfFyYuKpZe-1476083307252@nyuu
- ZlKnNtAsKtOzJrQdYeLjChXn-1476083344814@nyuu
- KhOeQfBsWbUhIcWsVyTkPvYk-1476083349482@nyuu
- XzOcMzWtFsFuJsQgPgBjSuKm-1476083383906@nyuu
- EcQgNgSfRhMbMoXlFcLwHmCe-1476083386110@nyuu
- MbSdXbExUwGtEkFeYdTlViQm-1476083386671@nyuu
- ZpZdPbRxAnKoWcDeErInHgFp-1476083389917@nyuu

**Comment by animetosho** [comment]
I must say, that completely slipped my mind. Excellent find and thanks a lot for reporting it!

Hopefully the above commit fixes it.
