### ISSUE TITLE
Build fails with node.js 12.7.0

### ISSUE THREAD

**Issue by IncredibleLaser** [animetosho/node-yencode#5]
Building this package (and by extension nyuu) fails with node.js 12.7.0 which is the current version. A build log is attached.
[yencode.log](https://github.com/animetosho/node-yencode/files/3439149/yencode.log)
Rolling back to an older version of node.js (here: 11.15.0) fixes the issue.

**Comment by animetosho** [comment]
Thanks!

I *think* the above should fix it. Would you be able to double check?

**Comment by IncredibleLaser** [comment]
Running `node-gyp rebuild` on the checked out source works now.

**Comment by animetosho** [comment]
Awesome, thanks for trying it out and getting back!
