### ISSUE TITLE
Errors trying to install yencode

### ISSUE THREAD

**Issue by ukrgukrg** [animetosho/node-yencode#7]
i am getting this output 

gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@10.18.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.18.0/node-v10.18.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.18.0/node-v10.18.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.18.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.18.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/Nyuu-0.3.8/node_modules/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/10.18.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.18.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.18.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/Nyuu-0.3.8/node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /root/Nyuu-0.3.8/node_modules) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-72-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/Nyuu-0.3.8/node_modules
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0

when i tried installing yencode in ~/Nyuu-0.3.8/node_modules

**Comment by animetosho** [comment]
What command are you using?

Try `npm install` *outside* of the node_modules folder (i.e. `~/Nyuu-0.3.8` in your example).
